/* generated configuration header file - do not edit */
#ifndef SF_CTSU_TUNING_CFG_H_
#define SF_CTSU_TUNING_CFG_H_
#define SF_CTSU_TUNING_CFG_PARAM_CHECK      (BSP_CFG_PARAM_CHECKING_ENABLE)

#define SF_CTSU_TUNING_CFG_CONNECTION       (2)

#define SF_CTSU_TUNING_CFG_THREAD_PRIORITY  (1)

#define SF_CTSU_TUNING_CFG_MODE_TUNING      (1)
#define SF_CTSU_TUNING_CFG_MODE_MONITOR     (2)

#define SF_CTSU_TUNING_CFG_MODE             (2)

#define SF_CTSU_TUNING_CFG_THREAD_STACK_SIZE    (1024)

#define SF_CTSU_TUNING_CFG_SCI_SIZE_CHECK_COUNT (2)

#define SF_CTSU_TUNING_CFG_SCI_BASE_DATA_SIZE (3)

#define WORKBENCH_COMMAND_USE       (1)

#endif /* SF_CTSU_TUNING_CFG_H_ */
